#ifndef LDEFINE_H_INCLUDED
#define LDEFINE_H_INCLUDED

#define GROUND 510
#define MAX_HEIGHT 260

bool JUMP = 1;
bool FALL = 0;
int type;

const int SCREEN_WIDTH = 1200;
const int SCREEN_HEIGHT = 600;

const int WALKING_ANIMATION_FRAMES = 6;
const int ONGROUND_ANIMATION_TOTAL = 1;
const int INAIR_ANIMATION_TOTAL = 4;
const int SPECIALFRUIT_ANIMATION = 1;

#define SPEED_INCREASEMENT 2
#define SCORE_INCREASEMENT 1
#define TIME_INCREASEMENT 1

#define ENEMY_MAX_HEIGHT 300
#define ENEMY_MIN_HEIGHT 330

#define RANGE 250
#define ENEMY1_RANGE 100
#define ENEMY2_RANGE 350
#define ENEMY3_RANGE 500

#define IN_AIR_ENEMY 1
#define ON_GROUND_ENEMY 0
#define ENEMY_SPEED 5
#define MAX_ENEMY_WIDTH 100

#define TEXT_YourScore_POSX 1000
#define TEXT_YourScore_POSY 10

#define TEXT_BestScore_POSX 1000
#define TEXT_BestScore_POSY 35

#define INSTRUCTIONS_POSX1 150
#define INSTRUCTIONS_POSY1 150
#define INSTRUCTIONS_POSX2 150
#define INSTRUCTIONS_POSY2 250
#define INSTRUCTIONS_POSX3 150
#define INSTRUCTIONS_POSY3 350
#define AUTHOR_POSX 600
#define AUTHOR_POSY 430
#define GAMEOVER_POSX 400
#define GAMEOVER_POSY 100
#define ENDGAME_POSX 350
#define ENDGAME_POSY 160

#define SCORE_POSX 1140
#define SCORE_POSY 10

#define HIGHSCORE_POSX 1140
#define HIGHSCORE_POSY 35

#define TIME_MAX 1000

#define SMALL_BUTTON 1
#define COMMON_BUTTON 2
#define RETURN_BUTTON 3

const int COMMON_BUTTON_WIDTH = 150;
const int COMMON_BUTTON_HEIGHT = 98;
const int RETURN_BUTTON_WIDTH = 100;
const int RETURN_BUTTON_HEIGHT = 78;
const int SMALL_BUTTON_WIDTH = 35;
const int SMALL_BUTTON_HEIGHT = 35;

const int PLAY_BUTTON_POSX = 500;
const int PLAY_BUTTON_POSY = 200;
const int HELP_BUTTON_POSX = 500;
const int HELP_BUTTON_POSY = 320;
const int EXIT_BUTTON_POSX = 500;
const int EXIT_BUTTON_POSY = 440;
const int PAUSE_BUTTON_POSX = 10;
const int PAUSE_BUTTON_POSY = 10;
const int CONTINUE_BUTTON_POSX = 10;
const int CONTINUE_BUTTON_POSY = 10;
const int AUDIO_BUTTON_POSX = 50;
const int AUDIO_BUTTON_POSY = 10;
const int RETURN_BUTTON_POSX = 25;
const int RETURN_BUTTON_POSY = 500;
const int SPECIALFRUIT_TEXT_POSX = 10;
const int SPECIALFRUIT_TEXT_POSY = 60;
const int SPECIALFRUIT_TIME_POSX = 120;
const int SPECIALFRUIT_TIME_POSY = 60;


#endif // LDEFINE_H_INCLUDED
